### ISSUE TITLE
Consider extending Layout directly

### ISSUE THREAD

**Issue by aarthificial** [hhenrichsen/motion-canvas-graphing#5]
Currently, the `Plot` node extends `Rect` which may not be an optimal choice.
`Rect` extends `Curve` which comes with a lot of overhead related to animating curves (`start`, `startArrow`, `startOffset`, `getPointAtDistance`, etc.). I don't think these features make sense in the context of a `Plot` node.

On top of that, `Curve` extends `Shape` which comes with a generalized style configuration (`fill`, `stroke`, etc.) that is not used by the current `Plot` implementation.

I'd recommend extending `Layout` directly to clear up the public interface and get rid of all unused properties.

**Comment by hhenrichsen** [comment]
I mainly overrode `Rect` rather than `Layout` because it allowed me to inherit the rect path for the `clip` property. I definitely can do this, but I was very lazy.

**Comment by aarthificial** [comment]
Oh, I haven't noticed the clip property in `LinePlot`
I'm afraid it will require a custom implementation regardless, because the `Rect`'s path doesn't account for `edgePadding`:
![image](https://github.com/hhenrichsen/motion-canvas-graphing/assets/64662184/0edff0c2-0fac-453b-a7e9-09375bb6f7d9)

**Comment by hhenrichsen** [comment]
I'm implementing `Layout` as of 33e2635, but there's probably more work to keep these clipped to the proper area, yeah.
